version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=combinator
      - POSTGRES_PASSWORD=combinator
      - POSTGRES_DB=combinator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
